# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["app_user"] }
[migrations_directory]
dir = "/Users/shoheiyamashita/myprj/react_sample/imageViewer2Test/database/diesel_schema/migrations"
