AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'nextjs-lambda SAM Template for Next.js on AWS

  '
Parameters:
  StackFamily:
    Type: String
    Default: nextjs-lambda-app
Globals:
  Function:
    Timeout: 3
    Tracing: Active
Resources:
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Timeout: 30
      Architectures:
      - x86_64
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: response_stream
          DEBUG: '*'
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      ImageUri: nextfunction:v1
    Metadata:
      DockerContext: /Users/shoheiyamashita/myprj/react_sample/imageViewer2Test/image_viewer_app
      DockerTag: v1
      Dockerfile: Dockerfile
      SamResourceId: NextFunction
Outputs:
  NextFunction:
    Value:
      Fn::GetAtt:
      - NextFunction
      - Arn
    Export:
      Name:
        Fn::Sub: ${StackFamily}-next-function-arn
  NextFunctionUrl:
    Value:
      Fn::GetAtt:
      - NextFunctionUrl
      - FunctionUrl
    Export:
      Name:
        Fn::Sub: ${StackFamily}-next-function-url
